'''Write a program that uses turtle graphics to draw 5 consecutive squares
of size  length, along the same base line, to the image on the board'''

import turtle
paper = turtle.Screen()
pen = turtle.Turtle()
pen.up()
length= 100
pen.goto(-250,50)
pen.down()
pen.right(90)
pen.forward(length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.up()
pen.goto(-130,50)
pen.down()
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.up()
pen.goto(-10,50)
pen.down()
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.up()
pen.goto(110,50)
pen.down()
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.up()
pen.goto(230,50)
pen.down()
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
pen.right(90)
pen.forward( length)
