flag=flagInitial= int(input("What are the initial lengths: "))
change=int(input("How much longer should each flag be: "))
import turtle
paper= turtle.Screen()
pen= turtle.Turtle()

pen.up()
pen.goto(-350,0)
pen.down()

for i in range(4):
    for i in range(3):
        pen.forward(flag)
        pen.right(120)
    pen.up()
    pen.forward(flag)
    pen.down()
    flag= flag+change
pen.left(30)
flag=flagInitial
for i in range(4):
    for i in range(3):
        pen.forward(flag)
        pen.right(120)
    pen.up()
    pen.forward(flag)
    pen.down()
    flag= flag+change
'''
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
flag= flag+change
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
flag= flag+change
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
flag= flag+change
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
flag= flag+change
pen.left(30)
flag= flagInitial
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
flag= flag+change
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
flag= flag+change
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
flag= flag+change
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.forward(flag)
pen.right(120)
pen.up()
pen.forward(flag)
pen.down()
'''
